name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/40 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://nepal-foreign-trade-dashboard.streamlit.app/